# Generated by Django 4.2.1 on 2023-05-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_plant_some_big_int_val_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='some_decimal_val',
            field=models.DecimalField(decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='some_money_val',
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
    ]
