# Generated by Django 4.2.1 on 2023-05-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_plant_some_decimal_val_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_confirmed_utc_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='forgot_password_key_expiration_utc_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_login_utc_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registration_utc_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='created_utc_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orgApiKey',
            name='created_utc_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orgApiKey',
            name='expiration_utc_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
