# Generated by Django 4.2.1 on 2023-05-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_customer_tac_id_customer_tac'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='is_test',
            field=models.BooleanField(null=True),
        ),
    ]
