# Generated by Django 4.2.1 on 2023-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_tac_tac_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tac',
            name='tac_id',
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
