# Generated by Django 4.2.1 on 2023-05-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_tac_tac_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='last_udpate_utc_date_time',
            new_name='last_update_utc_date_time',
        ),
        migrations.RenameField(
            model_name='customerrole',
            old_name='last_udpate_utc_date_time',
            new_name='last_update_utc_date_time',
        ),
        migrations.RenameField(
            model_name='dategreaterthanfilter',
            old_name='last_udpate_utc_date_time',
            new_name='last_update_utc_date_time',
        ),
        migrations.RenameField(
            model_name='errorlog',
            old_name='last_udpate_utc_date_time',
            new_name='last_update_utc_date_time',
        ),
        migrations.RenameField(
            model_name='flavor',
            old_name='last_udpate_utc_date_time',
            new_name='last_update_utc_date_time',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='last_udpate_utc_date_time',
            new_name='last_update_utc_date_time',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='last_udpate_utc_date_time',
            new_name='last_update_utc_date_time',
        ),
        migrations.RenameField(
            model_name='orgapikey',
            old_name='last_udpate_utc_date_time',
            new_name='last_update_utc_date_time',
        ),
        migrations.RenameField(
            model_name='orgcustomer',
            old_name='last_udpate_utc_date_time',
            new_name='last_update_utc_date_time',
        ),
        migrations.RenameField(
            model_name='pac',
            old_name='last_udpate_utc_date_time',
            new_name='last_update_utc_date_time',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='last_udpate_utc_date_time',
            new_name='last_update_utc_date_time',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='last_udpate_utc_date_time',
            new_name='last_update_utc_date_time',
        ),
        migrations.RenameField(
            model_name='tac',
            old_name='last_udpate_utc_date_time',
            new_name='last_update_utc_date_time',
        ),
        migrations.RenameField(
            model_name='tristatefilter',
            old_name='last_udpate_utc_date_time',
            new_name='last_update_utc_date_time',
        ),
    ]
