# Generated by Django 4.2.1 on 2023-05-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_last_udpate_utc_date_time_customer_last_update_utc_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tac',
            name='tac_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
