# Generated by Django 4.2.1 on 2023-05-14 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_tac_tac_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
