# Generated by Django 4.2.1 on 2023-05-14 20:46

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_plant_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='other_flavor',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='some_email_address',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='some_n_var_char_val',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='some_phone_number',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='some_text_val',
            field=models.TextField(max_length=builtins.max, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='some_var_char_val',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
